[build]
  command = "cd client && npm install && npm run build && ls -la dist"
  publish = "client/dist"
  environment = { NODE_VERSION = "22" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200