[build]
  command = "cd client && npm run build && ls -la dist"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200